### ISSUE TITLE
Does not work with Object.values/Object.keys

### ISSUE THREAD

**Issue by ctrlplusb** [theKashey/memoize-state#26]
```javascript
import memoizeState from "memoize-state";

const selector = memoizeState(s => {
  return Object.values(s.items).map(x => x.text);
});

const state = {
  items: {
    1: { text: "foo" }
  }
};

console.log(selector(state));
// expected ['foo']
// actual   ['foo']  ✅

const newState = {
  ...state,
  items: {
    ...state.items,
    2: { text: "bar" }
  }
};

console.log(selector(newState));
// expected ['foo', 'bar']
// actual   ['foo'] 🚩
```

[Codesandbox demo](https://codesandbox.io/s/2ovpqy7mvr)

**Comment by theKashey** [comment]
👍

**Comment by theKashey** [comment]
That's actually a good issue.
You are assessing deeply nested `text` property, and algorithm thinks that it's what you are interested in - not `item`, but only `item.text`. By the same long - not `items` but `item`. Result is clear - new stuff is ignored.

It's working for arrays, as long `length` property changes, but not for objects. The funny moment - it's impossible to solve this problem with the current algorithm.

Idea - for every enumeration operation(ownKeys proxy hook) "asses" a _secret property_ = concatenated keys, but this is not a quite ES5 polyfill compatible. I really don't want to use old _spread_guard_ logic.

@dai-shi - might be you have some bright ideas?

**Comment by dai-shi** [comment]
@theKashey 
If you can detect Object.values/Object.keys with the `ownKeys` handler, keep the property names in a new array, and use the array in `collectValuables` not to eliminate those property names.
How's that sound?
I'm not familar with ES5 polyfill.

**Comment by theKashey** [comment]
Any changes in object keys should be considered as an object update, as long as a new keys might appear, which were not recorded before. Proxies are proxying only existing keys.
```js
const selector = memoizeState(s => {
  return s.key1+s.key2
});

const state = {
  s1: "test",
};

console.log(selector(state));
// expected 'foo + undefined'
// actual   'foo + undefined'  ✅

const newState = {
  s1: "test",
  s2: "passes",
};

console.log(selector(newState));
// expected 'test passes'
// actual   'test undefined' 🚩
```

**Comment by theKashey** [comment]
The fix was added into the underlying `proxyequal`, but not yet released.

**Comment by ctrlplusb** [comment]
Wow that is exciting news 👍

**Comment by theKashey** [comment]
A new version released. @ctrlplusb - thank you for a good case.
