### ISSUE TITLE
Error if memoized function returns `null`

### ISSUE THREAD

**Issue by icehaunter** [theKashey/memoize-state#32]
Thanks for a great library! While trying to incorporate it into my project, I encountered the following issue.

Whenever a memoized function returns `null`, error is thrown instead.
```
Thrown:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at deproxifyResult (~/node_modules/memoize-state/dist/es5/call.js:72:12)
    at callIn (~/node_modules/memoize-state/dist/es5/call.js:155:16)
    at ms_ (~/node_modules/memoize-state/dist/es5/memoize.js:75:33)
```

Minimal representation: [https://runkit.com/embed/urero89rh25k](https://runkit.com/embed/urero89rh25k).

I think it should be possible to be able to return `null` value from the memoized function.

The fix seems to be to change [this line](https://github.com/theKashey/memoize-state/blob/4c0734fc6731d4552845cf36608852adcdb4da46/src/call.js#L39) from
```js
if (typeof result === 'object') { }
```
to
```js
if (typeof result === 'object' && result !== null) { }
```
but I am not familiar enough with the codebase to be sure.

**Comment by theKashey** [comment]
:) I've created many complex test cases, except the most simple ones. That's how it usually works :)

**Comment by theKashey** [comment]
`2.0.9` has been released. Thank you for the report.
