### ISSUE TITLE
Cache miss if function retuns undefined despite state access

### ISSUE THREAD

**Issue by icehaunter** [theKashey/memoize-state#35]
Good day! I have discovered a behaviour I think must be an error.

If a function conditionally returns `undefined` depending on the state, then it is not memoized even if the value is unchanged. 
The example function for memoization is:
```js
k = memoize((obj) => 'value' in obj && obj.value ? obj.value : undefined)
k({ value: false }) // Cache miss expected
k({ value: false }) // Cache miss unexpected
```
Minimal representation with stats: https://runkit.com/embed/qitl8tiuizhf

Thank you!

**Comment by theKashey** [comment]
So, that was a stupid mistake, about ignoring __all__ `!results` - `0`, `false`, `null`, `undefined` would be not counted as a "I do have a cache".

v2.0.12 released.

**Comment by icehaunter** [comment]
Thanks for the quick response!
Library overall is awesome, thanks a lot for it!

**Comment by theKashey** [comment]
Tell your friends about it. It's here already to a while, but haven't got any real traction.
