### ISSUE TITLE
IE11 broken by WeakSet use

### ISSUE THREAD

**Issue by bz2** [theKashey/memoize-state#36]
Recent changes to `memoize-state` and `proxyequal` adding `WeakSet` uses have broken the IE11 compatibility promise from the readme.

See #4 "Should work for IE11/Android without polyfills" for background.

Note, `WeakMap` is (mostly) supported by IE11 natively, but `WeakSet` is not:
https://caniuse.com/#search=weakmap
https://caniuse.com/#search=weakset

https://github.com/theKashey/memoize-state/commit/c6765f659e81d7858601b4733e7835de02e4ed6f means `memoize-state` >2.0.11 is broken

https://github.com/theKashey/proxyequal/commit/b498eb13a3738fcbbc95e00dde40c19a5304a2cb means `proxyequal` >2.1.0 is broken.

One workaround is pin at the compatible versions of the packages:
```diff
-    "memoize-state": "^2.0.7",
+    "memoize-state": "=2.0.10",
+    "proxyequal": "=2.0.9",
```

The other is include a `WeakSet` polyfill in applications that end up pulling in any of this code:
```js
import 'core-js/es/weak-set';
```

**Comment by theKashey** [comment]
First I have to measure how WeakSets are faster/slower than WeakMaps.

**Comment by vitalybaev** [comment]
Any update here?

**Comment by theKashey** [comment]
@vitalybaev - the new version `2.0.15` has been released
